CREATE TABLE ORDERS_GS (
  OrderID INT NOT NULL,
  StartDate DATE NOT NULL,
  TimeCompleted DATE NULL,
  CustomerID INT NOT NULL,
  StoreID INT NOT NULL,
  EmployeeID INT NOT NULL,
  PRIMARY KEY (OrderID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS_GS(CustomerID),
  FOREIGN KEY (StoreID) REFERENCES STORES_GS(StoreID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEES_GS(CustomerID)
);